ROUTINE RunScript
 #; We will run this routine to do the benchmark
Run()
{
 #; extract files if necessary from .data/in to .data/temp

 #; Start time
 Set startTime = $ZHOROLOG

 #; Insert the call to your method/rountine that
 #; - reads the csv files from ./data/in or .data/temp
 #; - processes data
 #; - creates output file in .data/out

 #; End time
 Set endTime = $ZHOROLOG
 #; Elapsed time in seconds
 Set elapsed = endTime - startTime
 Write "Elapsed time: ", elapsed, " seconds", !
}